ULABITOHelpDesk.AppOnline/Areas/Admin/Controllers/ProgramController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using ULABITOHelpDesk.DataAccess.Repository.IRepository;
using ULABITOHelpDesk.Models;
using ULABITOHelpDesk.Models.ViewModels;

namespace ULABITOHelpDesk.AppOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProgramController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProgramController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            ProgramVM programVM = new ProgramVM()
            {
                Program = new ProgramData(),
                DepartmentList = _unitOfWork.Department.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };
            if (id == null)
            {
                //this is for create
                return View(programVM);
            }
            //this is for edit
            programVM.Program = _unitOfWork.Program.Get(id.GetValueOrDefault());
            if (programVM.Program == null)
            {
                return NotFound();
            }
            return View(programVM);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProgramVM programVM)
        {

            if (ModelState.IsValid)
            {
                if (programVM.Program.Id == 0)
                {
                    programVM.Program.QueryId = Guid.NewGuid();
                    programVM.Program.IsActive = true;
                    programVM.Program.CreatedDate = DateTime.Now;
                    programVM.Program.CreatedBy = "423036";
                    programVM.Program.CreatedIp = "172.16.25.30";
                    programVM.Program.UpdatedDate = DateTime.Now;
                    programVM.Program.UpdatedBy = "423036";
                    programVM.Program.UpdatedIp = "172.16.25.30";
                    programVM.Program.IsDeleted = false;
                    _unitOfWork.Program.Add(programVM.Program);

                }
                else
                {
                    programVM.Program.UpdatedDate = DateTime.Now;
                    //program.UpdatedBy = User.Identity.Name;
                    //program.UpdatedIp = Request.HttpContext.Connection.LocalIpAddress.ToString();
                    programVM.Program.UpdatedBy = "423036";
                    programVM.Program.UpdatedIp = "172.16.25.30";
                    programVM.Program.IsDeleted = false;
                    _unitOfWork.Program.Update(programVM.Program);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            programVM.DepartmentList = _unitOfWork.Department.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            return View(programVM);
        }

        #region API Calls

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Program.GetAll(includeProperties: "Department");
            return Json(new { data = allObj });
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Program.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Program.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }

        #endregion
    }
}

ULABITOHelpDesk.AppOnline/Areas/Admin/Controllers/SchoolController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ULABITOHelpDesk.DataAccess.Repository.IRepository;
using ULABITOHelpDesk.Models;
using Microsoft.AspNetCore.Identity;

namespace ULABITOHelpDesk.AppOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Route("admin/school")]
    public class SchoolController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public SchoolController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
       
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            School school = new School();
            if (id == null)
            {
                //this is for create
                return View(school);
            }
            //this is for edit
            school = _unitOfWork.School.Get(id.GetValueOrDefault());
            if (school == null)
            {
                return NotFound();
            }
            return View(school);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(School school)
        {
            
            if (ModelState.IsValid)
            {
                if (school.Id == 0)
                {
                    school.QueryId = Guid.NewGuid();
                    school.IsActive = true;
                    school.CreatedDate = DateTime.Now;
                    school.CreatedBy = "423036";
                    school.CreatedIp = "172.16.25.30";
                    school.UpdatedDate = DateTime.Now;
                    school.UpdatedBy = "423036";
                    school.UpdatedIp = "172.16.25.30";
                    school.IsDeleted = false;
                    _unitOfWork.School.Add(school);

                }
                else
                {
                    school.UpdatedDate = DateTime.Now;
                    //school.UpdatedBy = User.Identity.Name;
                    //school.UpdatedIp = Request.HttpContext.Connection.LocalIpAddress.ToString();
                    school.UpdatedBy = "423036";
                    school.UpdatedIp = "172.16.25.30";
                    school.IsDeleted = false;
                    _unitOfWork.School.Update(school);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        #region API Calls

        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.School.GetAll().ToList();
            return Json(new {data = allObj});
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.School.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.School.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }

        #endregion
    }
}

ULABITOHelpDesk.AppOnline/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ULABITOHelpDesk.DataAccess.Repository.IRepository;
using ULABITOHelpDesk.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using ULABITOHelpDesk.DataAccess.Data;

namespace ULABITOHelpDesk.AppOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Route("admin/school")]
    public class UserController : Controller
    {

        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }



        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.Include(u => u.UserType).ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if (user.UserType == null)
                {
                    user.UserType = new UserType()
                    {
                        Name = ""
                    };
                }
            }

            return Json(new { data = userList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }
            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked, we will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Operation Successful." });
        }

        #endregion
    }
}

ULABITOHelpDesk.AppOnline/Areas/Student/Controllers/IssueController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using ULABITOHelpDesk.DataAccess.Repository.IRepository;
using ULABITOHelpDesk.Models;
using ULABITOHelpDesk.Models.ViewModels;
using ULABITOHelpDesk.Utility;

namespace ULABITOHelpDesk.AppOnline.Areas.Student.Controllers
{
    [Area("Student")]
    [Authorize(Roles = SD.Role_Student)]
    public class IssueController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly ILogger<IssueController> _logger;

        public IssueController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment, ILogger<IssueController> logger)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Viewed By: "+User.Identity.Name);
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            IssueInitiateVM issueInitiateVM = new IssueInitiateVM()
            {
                IssueInitiate = new IssueInitiate(),
                ProgrmaList = _unitOfWork.Program.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                IssueSubtypeList = _unitOfWork.IssueSubtype.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };
            if (id == null)
            {
                //this is for create
                return View(issueInitiateVM);
            }
            //this is for edit
            issueInitiateVM.IssueInitiate = _unitOfWork.IssueInitiate.Get(id.GetValueOrDefault());
            if (issueInitiateVM.IssueInitiate == null)
            {
                return NotFound();
            }
            _logger.LogInformation("Loaded By: " + User.Identity.Name);
            return View(issueInitiateVM);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(IssueInitiateVM issueInitiateVM)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images\issues");
                    var extenstion = Path.GetExtension(files[0].FileName);

                    if (issueInitiateVM.IssueInitiate.ImagePath != null)
                    {
                        //this is an edit and we need to remove old image
                        var imagePath = Path.Combine(webRootPath, issueInitiateVM.IssueInitiate.ImagePath.TrimStart('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                    {
                        files[0].CopyTo(filesStreams);
                    }
                    issueInitiateVM.IssueInitiate.ImagePath = @"\images\issues\" + fileName + extenstion;
                }
                else
                {
                    //update when they do not change the image
                    if (issueInitiateVM.IssueInitiate.Id != 0)
                    {
                        IssueInitiate objFromDb = _unitOfWork.IssueInitiate.Get(issueInitiateVM.IssueInitiate.Id);
                        issueInitiateVM.IssueInitiate.ImagePath = objFromDb.ImagePath;
                    }
                }


                if (issueInitiateVM.IssueInitiate.Id == 0)
                {
                    issueInitiateVM.IssueInitiate.QueryId = Guid.NewGuid();
                    //issueInitiateVM.IssueInitiate.IsActive = true;
                    issueInitiateVM.IssueInitiate.CreatedDate = DateTime.Now;
                    issueInitiateVM.IssueInitiate.CreatedBy = User.Identity.Name;
                    issueInitiateVM.IssueInitiate.CreatedIp = Request.HttpContext.Connection.LocalIpAddress.ToString();
                    issueInitiateVM.IssueInitiate.UpdatedDate = DateTime.Now;
                    issueInitiateVM.IssueInitiate.UpdatedBy = "423036";
                    issueInitiateVM.IssueInitiate.UpdatedIp = "172.16.25.30";
                    issueInitiateVM.IssueInitiate.IsDeleted = false;
                    _unitOfWork.IssueInitiate.Add(issueInitiateVM.IssueInitiate);
                    _unitOfWork.Save();
                    _logger.LogInformation("Created By: " + User.Identity.Name);
                }
                //else
                //{
                //    issueInitiateVM.IssueInitiate.UpdatedDate = DateTime.Now;
                //    //issueInitiate.UpdatedBy = User.Identity.Name;
                //    //issueInitiate.UpdatedIp = Request.HttpContext.Connection.LocalIpAddress.ToString();
                //    issueInitiateVM.IssueInitiate.UpdatedBy = User.Identity.Name;
                //    issueInitiateVM.IssueInitiate.UpdatedIp = "172.16.25.30";
                //    issueInitiateVM.IssueInitiate.IsDeleted = false;
                //    _unitOfWork.IssueInitiate.Update(issueInitiateVM.IssueInitiate);
                //    _unitOfWork.Save();
                //    _logger.LogInformation("Edited By: " + User.Identity.Name);
                //}

                return RedirectToAction(nameof(Index));
            }
            else
            {
                issueInitiateVM.ProgrmaList = _unitOfWork.Program.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
                issueInitiateVM.IssueSubtypeList = _unitOfWork.IssueSubtype.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
                if (issueInitiateVM.IssueInitiate.Id != 0)
                {
                    issueInitiateVM.IssueInitiate = _unitOfWork.IssueInitiate.Get(issueInitiateVM.IssueInitiate.Id);
                }
            }
            return View(issueInitiateVM);
        }

        #region API Calls

        [HttpGet]
        public IActionResult GetAll()
        {
            var claimsIdentity = User.Identity.Name;
            
            var allObj = _unitOfWork.IssueInitiate.GetAll(u => u.CreatedBy == claimsIdentity, includeProperties: "ProgramData,IssueSubtype");
            return Json(new { data = allObj });
        }


        #endregion
    }
}

ULABITOHelpDesk.AppOnline/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ULABITOHelpDesk.AppOnline/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ULABITOHelpDesk.AppOnline/Views/Shared/_Layout.cshtml
@using Dapper
@using ULABITOHelpDesk.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ULAB ITO HelpDesk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    @*ULAB ITO HelpDesk*@
                    <img src="~/Images/ULAB-logo-small.gif" height="50px" weight="120px" />
                </a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Instruction</a>
                        </li>*@
                        @if (User.IsInRole(SD.Role_SuperAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="School" asp-action="Index">School</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Department" asp-action="Index">Department</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Program" asp-action="Index">Program</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="IssueType" asp-action="Index">Issue Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="IssueSubtype" asp-action="Index">Issue Subcategory </a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="IssueInitiate" asp-action="Index">Issue Initiate</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Student))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Student" asp-controller="Issue" asp-action="Index">My Issue</a>
                                    <a class="dropdown-item" href="#">My Services</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_SuperAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="UserType" asp-action="Index">User Type</a>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Registration</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        }
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-primary">
        <div class="container">
            &copy; 2021 - All rights reserved ULAB
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/8f4bb5eabd.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>